name: Deploy to Hero-MyWebClass

on:
  push:
    branches:
      - main
      - development
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 45.55.97.234 >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@45.55.97.234 "echo 'SSH connection successful'"

      - name: Set deployment directory
        id: set-deploy-dir
        run: |
          BRANCH=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
          case "$BRANCH" in
            main)
              echo "DEPLOY_DIR=/var/www/production" >> $GITHUB_ENV ;;
            development)
              echo "DEPLOY_DIR=/var/www/dev" >> $GITHUB_ENV ;;
            QA)
              echo "DEPLOY_DIR=/var/www/qa" >> $GITHUB_ENV ;;
            *)
              echo "Unknown branch: $BRANCH" >&2
              exit 1 ;;
          esac

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@45.55.97.234 "mkdir -p ${{ env.DEPLOY_DIR }}"
          rsync -avz --progress --exclude '.git' --exclude 'node_modules' ./build/ root@45.55.97.234:${{ env.DEPLOY_DIR }}/
